### ISSUE TITLE
GetAddresses IndexOutofRangeException

### ISSUE THREAD

**Issue by alberk8** [Felandil/tangle-.net#10]
Hi,
I have the following where when the count is 15 or more the code would error out.  My suspicion is on the parallel for but I am not sure where to fix.

```
  Seed seedTwo = new Seed("SUPERDUPERSEEDTESTING9ABCFEKXOFOXOX");
  var generator = new AddressGenerator(seedTwo, SecurityLevel.Medium);
  // run on Intel i5-4590
  var addr =  generator.GetAddresses(0, 15);

```

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Tangle.Net.Cryptography.AddressGenerator.GetAddresses(Int32 startIndex, Int32 count)
   at TangleNet.Program.Main(String[] args) in E:\Project\DLT\TangleNet\Program.cs:line 28

Inner Exception 1:
IndexOutOfRangeException: Index was outside the bounds of the array.
```

**Comment by Felandil** [comment]
Should be resolved now. Feedback would be much appreciated! :)
