### ISSUE TITLE
Exception: 'Command getTrytes failed!'

### ISSUE THREAD

**Issue by SiliconDroid** [Felandil/tangle-.net#15]
Hi, thanks @Felandil and other contribs for devving this code, it's nicely put together, clean structure and comments!

Running: FindUsedAddressesWithTransactionsExample works OK for me (although the last address reports zero balance?).

Running: GetAccountDataExample I get the exception below thrown every time, have tried my own VPS node and also setting to carriota field and trying it on many random nodes in the field. Always get the following exception:

`Tangle.Net.Repository.Client.IotaApiException
  HResult=0x80131500
  Message=Command getTrytes failed!
  Source=Tangle.Net
  StackTrace:
   at Tangle.Net.Repository.Client.RestIotaClient.ValidateResponse[T](IRestResponse'1 response, String commandName) in C:\Development\iota\iota_dot_net\Tangle.Net\Tangle.Net\Repository\Client\RestIotaClient.cs:line 142
   at Tangle.Net.Repository.Client.RestIotaClient.ExecuteParameterizedCommand[T](IReadOnlyCollection'1 parameters) in C:\Development\iota\iota_dot_net\Tangle.Net\Tangle.Net\Repository\Client\RestIotaClient.cs:line 36
   at Tangle.Net.Repository.RestIotaRepository.GetTrytes(IEnumerable'1 hashes) in C:\Development\iota\iota_dot_net\Tangle.Net\Tangle.Net\Repository\RestIotaCoreRepository.cs:line 327
   at Tangle.Net.Repository.RestIotaRepository.GetBundles(IEnumerable'1 transactionHashes, Boolean includeInclusionStates) in C:\Development\iota\iota_dot_net\Tangle.Net\Tangle.Net\Repository\RestIotaExtendedRepository.cs:line 282
   at Tangle.Net.Repository.RestIotaRepository.GetAccountData(Seed seed, Boolean includeInclusionStates, Int32 securityLevel, Int32 addressStartIndex, Int32 addressStopIndex) in C:\Development\iota\iota_dot_net\Tangle.Net\Tangle.Net\Repository\RestIotaExtendedRepository.cs:line 182
   at Tangle.Net.Examples.Examples.Api.GetAccountDataExample.Execute() in C:\Development\iota\iota_dot_net\Tangle.Net\Tangle.Net.Examples\Examples\Api\GetAccountDataExample.cs:line 26
   at Tangle.Net.Examples.Program.ExecuteApiExample() in C:\Development\iota\iota_dot_net\Tangle.Net\Tangle.Net.Examples\Program.cs:line 93
   at Tangle.Net.Examples.Program.Main(String[] args) in C:\Development\iota\iota_dot_net\Tangle.Net\Tangle.Net.Examples\Program.cs:line 32
`

**Comment by Felandil** [comment]
Hey! Thanks for reporting! The problem with getting the account state is prolly a result of to many transactions on a certain address in the seed. Internally every transaction is (currently) queried on it's own which means a lot of requests to the node. Since most nodes have a request limit set, that could be the problem.

I'll see if it is possible to change the whole process to bulk requesting, thus reducing the amount of needed requests.

**Comment by Felandil** [comment]
The problem should be fixed now, even though the error might occur for a few seeds that have to much transactions on them. 
Sadly that is something that can not really be fixed (afaik). Please give a short feedback, if everything works now!

**Comment by SiliconDroid** [comment]
The getTryte exception doesn't fire now.

But running GetAccountDataExample seems to get stuck:

Seed has only address[0] in use.
Address has like 10 TX on it.
Does not return, tried 15 min run in release mode.
40% CPU, 30 ... 40MB process memory (avg).

Running in debug... call stack seems to reveal a lot of curl when stuck.

**Comment by Felandil** [comment]
It took 12 mins to receive all information on a seed (carrIOTA seed) that contained a lot of bundles/transactions. This can't be really avoided, because GetAccountData requests all transactions of all bundles on that seed.

I'd suggest to use GetBalances and/or query bundles, if really needed. I hope that helps. Since there is no real solution to the problem, I'll close the issue tomorrorw.

**Comment by SiliconDroid** [comment]
Thanks for the info, that explains it, yes I tried it on a seeds address[0] that has had multiple carriota receives, massive bundles. So it was chugging along and it would have got there in the end. GetBalances works a treat, there is no need for me to get all transaction bundles.
